/*
 * This source file was generated by the Gradle 'init' task
 */
package prism.gradle;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'prism.gradle.base' plugin.
 */
class PrismBasePluginTest {
  @Test void pluginRegistersATask() {
    // Create a test project and apply the plugin
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("prism.gradle.base");

    // Verify the result
    assertNotNull(project.getTasks().findByName("assemble"), "registers assemble task");
    assertNotNull(project.getTasks().findByName("check"), "registers check task");
    assertNotNull(project.getTasks().findByName("build"), "registers build task");
  }
}
