tls:
  certificates:
    - certFile: /certs/_.traefik.localhost/cert.pem
      keyFile: /certs/_.traefik.localhost/key.pem
      stores:
        - default
    - certFile: /certs/_.nginx.localhost/cert.pem
      keyFile: /certs/_.nginx.localhost/key.pem
    - certFile: /certs/_.java-11.localhost/cert.pem
      keyFile: /certs/_.java-11.localhost/key.pem
    - certFile: /certs/_.k3s.localhost/cert.pem
      keyFile: /certs/_.k3s.localhost/key.pem

  stores:
    default: {}
