/*
 * This source file was generated by the Gradle 'init' task
 */
package prism.gradle;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class PrismBasePlugin implements Plugin<Project> {
    public void apply(Project project) {
      // Register assemble task
      project.getTasks().register("assemble", task -> {
          task.doLast(s -> System.out.println("Assemble complete."));
      });

      // Register check task
      project.getTasks().register("check", task -> {
          task.doLast(s -> System.out.println("Check complete."));
      });

      // Register build task
      project.getTasks().register("build", task -> {
          task.doLast(s -> System.out.println("Build complete."));
      });
    }
}
